import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Background } from "@/components/Background";
import { CursorGlow } from "@/components/CursorGlow";
import { BackToTop } from "@/components/BackToTop";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import NextTopLoader from "nextjs-toploader";
import { Preloader } from "@/components/Preloader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <>
          <NextTopLoader color="var(--secondary)" showSpinner={false} />
          <Preloader />
          <Background />
          <CursorGlow />
          <Navbar />
          <main className="relative pt-24 min-h-screen">{children}</main>
          <Footer />
          <BackToTop />
        </>
      </body>
    </html>
  );
}
